# Name of the final executable
TARGET = main

# Source files
WRAPPER_SRC = opencv_wrapper.cpp
ADA_SRC = main.adb

# Shared library generated by the wrapper
WRAPPER_LIB = libopencv_wrapper.so

# Compilation options
CXX = g++
CXXFLAGS = -fPIC -shared $(shell pkg-config --cflags opencv4)
LDFLAGS = -L. -lopencv_wrapper $(shell pkg-config --libs opencv4) -Wl,-rpath=.
GNATMAKE = gnatmake

# Rule to compile the entire project
all: $(TARGET)

# Compile the C++ wrapper into a shared library
$(WRAPPER_LIB): $(WRAPPER_SRC)
	$(CXX) $(CXXFLAGS) -o $@ $<

# Compile the Ada program, linking with the wrapper library and OpenCV
$(TARGET): $(ADA_SRC) $(WRAPPER_LIB)
	$(GNATMAKE) $(ADA_SRC) -largs $(LDFLAGS)

# Clean generated files
clean:
	rm -f $(TARGET) $(TARGET).ali $(TARGET).o $(WRAPPER_LIB)
	rm -f *.o *.ali

# Phony targets
.PHONY: all clean

